vulnerabilities:
  - id: CVE-2026-33816
    expired_at: 2026-08-01
    statement: Accept the risk
  - id: CVE-2026-29181
    expired_at: 2026-08-01
    statement: Accept the risk
  - id: CVE-2026-39883
    expired_at: 2026-08-01
    statement: Accept the risk